# Generated by Django 5.2.4 on 2025-07-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_partner_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='location',
            field=models.CharField(default='Kathmandu', max_length=255),
        ),
    ]
