# Generated by Django 5.2.3 on 2025-07-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addBlogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=8),
        ),
    ]
