# Generated by Django 4.2.21 on 2025-07-07 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addBlogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addblog',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='addblog',
            name='author',
            field=models.CharField(default='Anoynymous', max_length=50),
        ),
    ]
